# Generated by Django 5.1.2 on 2024-10-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('prioridad', models.IntegerField()),
                ('estado', models.TextField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente')),
                ('completada', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateField()),
                ('horaVencimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('contraseña', models.TextField(max_length=100)),
                ('fechaRegistro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.etiqueta')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='etiquetasDeTareas',
            field=models.ManyToManyField(through='creacionModelo.Tarea_Etiqueta', to='creacionModelo.tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='creacionModelo.usuario'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('duracionEstimada', models.FloatField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.tarea')),
                ('creador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='creacionModelo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=300)),
                ('fechaComentario', models.DateField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.tarea')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDeTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(max_length=300)),
                ('fechaAsignacion', models.DateField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarioAsignado',
            field=models.ManyToManyField(related_name='proyectos_asignados', through='creacionModelo.Usuario_Proyecto', to='creacionModelo.usuario'),
        ),
        migrations.CreateModel(
            name='Usuarios_Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacionModelo.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuariosAsignados',
            field=models.ManyToManyField(related_name='tareas_asignadas', through='creacionModelo.Usuarios_Tareas', to='creacionModelo.usuario'),
        ),
    ]
